pcl_grid_map_extraction:
  num_processing_threads: 4
  cloud_transform:
    translation:
      x: -735762.505400
      y: -2978489.25386
      z: -909.607
    rotation: #intrinsic rotation X-Y-Z (r-p-y)sequence
      r: 0.0
      p: 0.0
      y: 0.0
  cluster_extraction:
    cluster_tolerance: 1
    min_num_points: 4
    max_num_points: 1000000
  outlier_removal:
    is_remove_outliers: true
    mean_K: 10
    stddev_threshold: 1.0
  downsampling:
    is_downsample_cloud: true
    voxel_size:
      x: 0.5
      y: 0.5
      z: 0.5
  grid_map:
    min_num_points_per_cell: 4
    resolution: 1

    
       
